# -*- coding: utf-8 -*-
"""Recolección desde la web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZpDxRwcEzr0tVOvSe6Nhccrt_pPjZu3
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

def datos_establecimientos():
    # URL del SLEP Chiloé
    url = "https://slepchiloe.gob.cl/establecimientos-educacionales/"

    # Petición HTTP
    headers = {'User-Agent': 'Mozilla/5.0'}
    respuesta = requests.get(url, headers=headers)

    if respuesta.status_code != 200:
        print("Error al acceder a la página")
        return None

    # Parsear HTML
    soup = BeautifulSoup(respuesta.text, 'html.parser')

    # Buscar tabla
    tabla = soup.find('table')
    if not tabla:
        print("No se encontró la tabla en la página")
        return None

    # Extraer datos
    colegios = []
    for fila in tabla.find_all('tr')[1:]:
        columnas = fila.find_all(['td', 'th'])

        if len(columnas) >= 5:
            datos = {
                "Nombre Establecimiento": columnas[0].get_text(strip=True),
                "Comuna": columnas[1].get_text(strip=True),
                "Dirección": columnas[2].get_text(strip=True),
                "Teléfono": columnas[3].get_text(strip=True),
                "Sitio Web": columnas[4].get_text(strip=True)
            }
            colegios.append(datos)

    # Convertir a DataFrame
    df = pd.DataFrame(colegios)
    return df


if __name__ == "__main__":
    resultado = datos_establecimientos()

    if resultado is not None:
        print("### Datos Recolectados ###")
        print(resultado)

        # Guardar CSV
        resultado.to_csv("establecimientos_slep_chiloe.csv", index=False)

import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL
url = "https://slepchiloe.gob.cl/establecimientos-educacionales/"

# Request
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# Buscar todas las tablas
tables = soup.find_all("table")

data = []

#Extrae tablas
for informacion in tables:
    rows = informacion.find_all("tr")

    for row in rows[1:]:  # saltar encabezado
        cols = row.find_all("td")

        if len(cols) >= 5:
            nombre = cols[0].get_text(strip=True)
            comuna = cols[1].get_text(strip=True)
            direccion = cols[2].get_text(strip=True)
            telefono = cols[3].get_text(strip=True)
            sitioweb = cols[4].get_text(strip=True)

            data.append([nombre, comuna, direccion, telefono, sitioweb])

# Mostrar
df = pd.DataFrame(data, columns=[
    "Nombre Establecimiento",
    "Comuna",
    "Dirección",
    "Teléfono",
    "Sitio Web"
])

# Mostrar
df.head()

"""# Colegios SLEPS

https://educacionpublica.gob.cl/sleps/ver-todos-los-sleps/

"""